# Pose Transformer Project Configuration

[data]
data_dir = "./data/chatsign_200_conf_v2"          # pkl数据目录 (路径相对于项目根目录)
sequence_length = 16          # 输入序列的长度（看过去多少帧）
n_kps = 128                   # 每帧的关键点数量
features_per_kp = 3           # 每个关键点的特征数 (x, y) # confidence

[model]
# d_model 必须能被 n_head 整除
d_model = 512                 # Transformer的内部维度
n_head = 8                    # 多头注意力的头数
num_encoder_layers = 6        # Transformer编码器层数
dim_feedforward = 2048        # 前馈网络的维度
dropout = 0.1                 # Dropout比例

[training]
batch_size = 32
learning_rate = 0.0001
num_epochs = 100
# device: "cuda", "cpu", or "auto" for automatic detection
device = "auto"

[masking]
spatial_mask_ratio = 0.05     # 空间（关键点）掩码比例
temporal_mask_ratio = 0.15    # 时间（帧）掩码比例
confidence_threshold = 0.3

[loss_weights]
# 这些是超参数，需要仔细调整。建议从一个较小的值开始。
lambda_recon = 1.0     # 重建损失权重
lambda_vel = 0.1     # 速度损失权重
lambda_accel = 0.1   # 加速度损失权重
lambda_bone = 0.0    # 骨骼长度损失权重
lambda_tv = 0.01     # 总变差正则化权重

[skeleton]
# 定义骨骼连接。这里的索引是你134个关键点中的索引。
# 这是一个示例，你需要根据你的关键点定义来填充这个列表！
# 例如：[[左肩, 左肘], [左肘, 左腕], ...]
bones = [
  [0, 1], [1, 2], [2, 3],  # 示例骨骼1
  [5, 6], [6, 7], [7, 8]   # 示例骨骼2
]