# Pose Transformer Project Configuration

[data]
data_dir = "./data/chatsign_200_wo_retarget"          # pkl数据目录 (路径相对于项目根目录)
video_dir = "./data/chatsign_200_videos"
sequence_length = 16          # 输入序列的长度（看过去多少帧）
n_kps = 128                   # 每帧的关键点数量
features_per_kp = 3           # 每个关键点的特征数 (x, y) # confidence

[model]
version = "v3"                # Model version to use
# d_model 必须能被 n_head 整-除
d_model = 512                 # Transformer的内部维度
n_head = 8                    # 多头注意力的头数
num_encoder_layers = 6        # Transformer编码器层数
dim_feedforward = 2048        # 前馈网络的维度
dropout = 0.1                 # Dropout比例

# --- Decoder settings (for V3 model) ---
decoder_d_model = 256         # Decoder的内部维度 (可以更小)
decoder_n_head = 4            # Decoder的多头注意力的头数
num_decoder_layers = 2        # Decoder的层数 (可以更少)
decoder_dim_feedforward = 1024 # Decoder的前馈网络的维度

[training]
batch_size = 32
learning_rate = 0.0001
num_epochs = 100
# device: "cuda", "cpu", or "auto" for automatic detection
device = "auto"

[masking]
total_mask_ratio = 0.75       # (For V3 Model) 掩码总比例
spatial_mask_ratio = 0.05     # 空间（关键点）掩码比例
temporal_mask_ratio = 0.15    # 时间（帧）掩码比例
confidence_threshold = 0.3

[loss_weights]
# 这些是超参数，需要仔细调整。建议从一个较小的值开始。
lambda_recon = 1.0     # 重建损失权重
lambda_vel = 0.1     # 速度损失权重
lambda_accel = 0.1   # 加速度损失权重
lambda_bone = 0.1    # 骨骼长度损失权重
lambda_tv = 0.01     # 总变差正则化权重