#!/usr/bin/env python3
"""
Denormalizes keypoints using saved transformation parameters from a PKL file.

Input Format:
A list of T dictionaries, generated by 'normalize_with_params.py'.
[
    {'keypoints': (128, 3), 'subset': ..., 'norm_params': {...}},
    ...
]

Output Format:
Mirrors the input format, but with keypoints restored to original pixel coordinates.
"""

import pickle
import numpy as np
import argparse
from tqdm import tqdm

def denormalize_pkl(input_path, output_path):
    print(f"Loading normalized data from {input_path}...")
    with open(input_path, 'rb') as f:
        data_list = pickle.load(f)

    if not isinstance(data_list, list) or 'norm_params' not in data_list[0]:
        raise TypeError("Input file must be a list of dicts containing 'norm_params'.")
    
    T = len(data_list)
    print(f"Found {T} frames to denormalize.")

    BODY_INDICES = slice(0, 18)
    FACE_INDICES = slice(18, 86)
    LEFT_HAND_INDICES = slice(86, 107)
    RIGHT_HAND_INDICES = slice(107, 128)
    
    output_data_list = []
    print("Denormalizing keypoints...")

    for i in tqdm(range(T), desc="Processing Frames"):
        frame_data = data_list[i]
        
        # This can be either ground truth normalized data or your model's predictions
        norm_kps = np.array(frame_data['keypoints']) 
        norm_params = frame_data['norm_params']
        
        denormalized_frame = np.zeros_like(norm_kps)
        
        body_scale = norm_params.get('body_scale', 0)
        if body_scale == 0:
            output_data_list.append({
                'keypoints': denormalized_frame, 
                'subset': frame_data['subset']
            })
            continue

        # --- Denormalize Body ---
        # Reverse: norm = ((orig - offset) / scale - 0.5) * 2
        # --> orig = ((norm / 2) + 0.5) * scale + offset
        body_offset = norm_params['body_offset']
        norm_body_coords = norm_kps[BODY_INDICES, :2]
        orig_body_coords = ((norm_body_coords / 2) + 0.5) * body_scale + body_offset
        denormalized_frame[BODY_INDICES, :2] = orig_body_coords
        
        # --- Denormalize Other Parts ---
        parts_to_process = {
            'face': FACE_INDICES,
            'left_hand': LEFT_HAND_INDICES,
            'right_hand': RIGHT_HAND_INDICES,
        }
        
        for part_name, indices in parts_to_process.items():
            # Reverse: norm = (orig - center) / scale
            # --> orig = norm * scale + center
            center_point = norm_params[f'{part_name}_center']
            norm_part_coords = norm_kps[indices, :2]
            orig_part_coords = (norm_part_coords * body_scale) + center_point
            denormalized_frame[indices, :2] = orig_part_coords
            
        # Restore confidence scores (they were never changed)
        denormalized_frame[:, 2] = norm_kps[:, 2]

        output_data_list.append({
            'keypoints': denormalized_frame,
            'subset': frame_data['subset']
        })

    print(f"\nSaving denormalized data to {output_path}...")
    with open(output_path, 'wb') as f:
        pickle.dump(output_data_list, f)

    print("Done!")
    print(f"  - Keypoints have been restored to their original coordinate space.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Denormalize pose data using saved parameters.")
    parser.add_argument("--input_path", type=str, help="Path to the normalized .pkl file (containing norm_params).")
    parser.add_argument("--output_path", type=str, help="Path for the output denormalized .pkl file.")
    args = parser.parse_args()
    denormalize_pkl(args.input_path, args.output_path)